
def print_divider():
    print '*' * 80


def count_melons(orders_file):
    """
    Takes a file and returns a dictionary with the amount of each type of melon that was sold.
    """

    fin = open(orders_file)
    melon_tallies = {"Musk":0, "Hybrid":0, "Watermelon":0, "Winter": 0}

    for line in fin:  # switched variable name from l to line to be more clear
        data = line.split("|")
        melon_type = data[1]
        melon_count = int(data[2])
        melon_tallies[melon_type] += melon_count

    return melon_tallies


def calculate_revenue(melon_tallies):
    """
    Takes a dictionary of melon tallies and prints the sales revenue.
    """

    melon_prices = { "Musk": 1.15, "Hybrid": 1.30, "Watermelon": 1.75, "Winter": 4.00 }
    total_revenue = 0

    for melon_type in melon_tallies:
        price = melon_prices[melon_type]
        revenue = price * melon_tallies[melon_type]
        total_revenue += revenue
        print "We sold %d %s melons at %0.2f each for a total of %0.2f" % (melon_tallies[melon_type], melon_type, price, revenue)


def separate_sales(sales_file):
    """
    Takes a sales report file and prints total revenue generated by salespeople and online sales.
    """
    fin = open(sales_file)
    sales_revenue = [0, 0] # [internet sales, salespeople]

    for line in fin:
        d = line.split("|")
        if d[1] == "0":
            sales_revenue[0] += float(d[3])
        else:
            sales_revenue[1] += float(d[3])
    print "Salespeople generated %0.2f in revenue." % sales_revenue[1]
    print "Internet sales generated %0.2f in revenue." % sales_revenue[0]
    if sales_revenue[1] > sales_revenue[0]:
        print "Guess there's some value to those salespeople after all."
    else:
        print "Time to fire the sales team! Online sales rule all!"


def print_CEO_report(melon_file, sales_file):
    print_divider()
    calculate_revenue(count_melons(melon_file))
    print_divider()
    separate_sales(sales_file)
    print_divider()

print_CEO_report("orders-by-type.txt", "orders-with-sales.txt")
